"""initial schema

Revision ID: 553a5f31132d
Revises: 
Create Date: 2026-03-07 11:53:17.522389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553a5f31132d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('network', sa.String(), nullable=False),
    sa.Column('annual_fee', sa.Integer(), nullable=False),
    sa.Column('fx_fee_bps', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_is_active'), 'cards', ['is_active'], unique=False)
    op.create_index(op.f('ix_cards_issuer'), 'cards', ['issuer'], unique=False)
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    op.create_table('reward_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('flat_points', sa.Integer(), nullable=False),
    sa.Column('cap_amount', sa.Float(), nullable=True),
    sa.Column('cap_period', sa.String(), nullable=True),
    sa.Column('txn_min', sa.Float(), nullable=True),
    sa.Column('txn_max', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_rules_card_id'), 'reward_rules', ['card_id'], unique=False)
    op.create_index(op.f('ix_reward_rules_category'), 'reward_rules', ['category'], unique=False)
    op.create_index(op.f('ix_reward_rules_channel'), 'reward_rules', ['channel'], unique=False)
    op.create_index(op.f('ix_reward_rules_country'), 'reward_rules', ['country'], unique=False)
    op.create_index(op.f('ix_reward_rules_is_active'), 'reward_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_reward_rules_priority'), 'reward_rules', ['priority'], unique=False)
    op.create_table('user_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_cards_card_id'), 'user_cards', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_cards_user_id'), 'user_cards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_cards_user_id'), table_name='user_cards')
    op.drop_index(op.f('ix_user_cards_card_id'), table_name='user_cards')
    op.drop_table('user_cards')
    op.drop_index(op.f('ix_reward_rules_priority'), table_name='reward_rules')
    op.drop_index(op.f('ix_reward_rules_is_active'), table_name='reward_rules')
    op.drop_index(op.f('ix_reward_rules_country'), table_name='reward_rules')
    op.drop_index(op.f('ix_reward_rules_channel'), table_name='reward_rules')
    op.drop_index(op.f('ix_reward_rules_category'), table_name='reward_rules')
    op.drop_index(op.f('ix_reward_rules_card_id'), table_name='reward_rules')
    op.drop_table('reward_rules')
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_index(op.f('ix_cards_issuer'), table_name='cards')
    op.drop_index(op.f('ix_cards_is_active'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
